import { Artisan, Product, Inquiry, SalesRecord, CategoryDistribution } from '../types';

export const initialArtisan: Artisan = {
  id: 'artisan-ramswaroop',
  name: 'Ramswaroop Sharma',
  nameHi: 'रामस्वरूप शर्मा',
  phone: '+91 98290 44211',
  location: 'Kot Jewar, Jaipur District',
  state: 'Rajasthan',
  craftSpecialty: 'Jaipur Blue Pottery & Glazed Ceramics',
  experienceYears: 34,
  cooperativeName: 'Sanganer Vikas Hastshilp Samiti',
  isCooperativeMember: true,
  rating: 4.9,
  totalSales: 485000,
  activeListingsCount: 8,
  openInquiriesCount: 3,
  avatar: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=400&q=80',
  bio: 'Third-generation master artisan practicing the GI-certified art of Jaipur Blue Pottery. Our workshop utilizes non-clay quartz stone dough fired at low kiln temperatures with cobalt oxide and copper blues.',
  bioHi: 'जयपुर ब्लू पॉटरी के तीसरी पीढ़ी के उस्ताद कारीगर। हमारी कार्यशाला बिना मिट्टी के, केवल क्वार्ट्ज पत्थर, मुल्तानी मिट्टी और प्राकृतिक रंगों से हस्तनिर्मित कलाकृतियां बनाती है।'
};

export const initialProducts: Product[] = [
  {
    id: 'prod-surahi-01',
    title: 'Jaipur Blue Pottery Floral Surahi (Water Pitcher)',
    titleHi: 'पारंपरिक जयपुर ब्लू पॉटरी फ्लोरल सुराही',
    description: 'Authentic GI-tagged Jaipur Blue Pottery water vessel adorned with hand-painted Persian floral arabesques in traditional cobalt and turquoise glazes.',
    descriptionHi: 'हाथ से चित्रित पारंपरिक कोबाल्ट और फिरोज़ी रंगों वाली जीआई प्रमाणित जयपुर ब्लू पॉटरी सुराही।',
    culturalStory: 'Derived from Turko-Persian origins introduced during the reign of Maharaja Sawai Ram Singh II in the 19th century. Blue Pottery does not use traditional river clay; instead, the body is formed from quartz stone powder, Fuller’s earth, and katira gond gum.',
    culturalStoryHi: '19वीं शताब्दी में महाराजा सवाई राम सिंह द्वितीय के संरक्षण में विकसित। इसमें साधारण मिट्टी का उपयोग नहीं होता, बल्कि क्वार्ट्ज चूर्ण, मुल्तानी मिट्टी और प्राकृतिक गोंद से ढाला जाता है।',
    category: 'pottery',
    priceMin: 1450,
    priceMax: 1850,
    finalPrice: 1650,
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Ramswaroop Sharma',
    artisanLocation: 'Kot Jewar, Jaipur, Rajasthan',
    artisanPhone: '+91 98290 44211',
    craftOrigin: 'Jaipur Heritage Cluster, Rajasthan (GI #33)',
    materials: ['Quartz Stone Powder', 'Fuller’s Earth (Multani Mitti)', 'Cobalt Oxide', 'Copper Glaze'],
    stockQuantity: 50,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-RAJ-0033',
    tags: ['Blue Pottery', 'GI Certified', 'Jaipur Craft', 'Hand Painted', 'Cobalt Glaze'],
    detectedLanguage: 'hi',
    audioTranscript: 'यह सुराही मैंने और मेरे बेटे ने मिलकर बनाई है। इसमें क्वार्ट्ज पत्थर और तांबे के नीले रंग का लेप किया गया है।',
    createdAt: '2026-08-14T10:30:00Z'
  },
  {
    id: 'prod-dhokra-02',
    title: 'Bastar Lost-Wax Bell Metal (Dhokra) Nandi Figurine',
    titleHi: 'बस्तर ढोकरा कांस्य नंदी शिल्प (लॉस्ट-वैक्स पद्धति)',
    description: 'Hand-cast tribal bronze bell metal Nandi bull created using the ancient 4,000-year-old cire perdue (lost wax) metal casting technique.',
    descriptionHi: '4000 वर्ष पुरानी पारंपरिक ढोकरा लॉस्ट-वैक्स धातु ढलाई तकनीक से बना हस्तनिर्मित नंदी बैल।',
    culturalStory: 'Practiced by the Ghadwa tribal community of Bastar for millennia, Dhokra metal casting requires creating a clay core, winding beeswax threads to carve intricate ornamentation, and casting with molten scrap brass and bell metal.',
    culturalStoryHi: 'बस्तर के घड़वा समुदाय द्वारा पीढ़ियों से संरक्षित ढोकरा शिल्प। प्रत्येक कृति मोम के धागों से हाथों द्वारा गढ़ी जाती है, जिससे हर मूर्ति अपने आप में अद्वितीय होती है।',
    category: 'metal',
    priceMin: 2200,
    priceMax: 2800,
    finalPrice: 2500,
    images: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Sukhdev Ghadwa',
    artisanLocation: 'Kondagaon, Bastar, Chhattisgarh',
    artisanPhone: '+91 94252 88190',
    craftOrigin: 'Bastar Tribal Craft Cluster (GI #83)',
    materials: ['Bell Metal (Kansa)', 'Recycled Brass', 'Beeswax', 'River Clay'],
    stockQuantity: 7,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-CG-0083',
    tags: ['Dhokra Art', 'Lost Wax', 'Bastar Tribal', 'Bell Metal', 'GI Heritage'],
    detectedLanguage: 'hi',
    audioTranscript: 'यह नंदी हमने पुरानी घंटी धातु और मधुमक्खी के मोम के तारों से सांचे में ढाला है।',
    createdAt: '2026-08-18T14:15:00Z'
  },
  {
    id: 'prod-banarasi-03',
    title: 'Handloom Pure Mulberry Silk Banarasi Kadhwa Stole',
    titleHi: 'हथकरघा शुद्ध शहतूत रेशम बनारसी कढ़वा स्टोल',
    description: 'Heirloom quality hand-woven Banarasi silk stole featuring delicate floral shikargah motifs woven with tested gold and silver zari threads.',
    descriptionHi: 'विशुद्ध शहतूत रेशम और सुनहरी ज़री से बुना हुआ हथकरघा बनारसी कढ़वा स्टोल।',
    culturalStory: 'In the revered Kadhwa technique, each floral buti motif is individually engraved on the pit loom without loose floats on the reverse side. A single master weaver spends over 20 days on each handcrafted stole.',
    culturalStoryHi: 'कढ़वा बुनाई बनारस की सबसे कठिन और मूल्यवान कला है जिसमें प्रत्येक बूटा अलग-अलग हाथ से बुना जाता है।',
    category: 'textiles',
    priceMin: 4200,
    priceMax: 5400,
    finalPrice: 4800,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Mohammad Shahid Ansari',
    artisanLocation: 'Madanpura, Varanasi, Uttar Pradesh',
    artisanPhone: '+91 97920 11984',
    craftOrigin: 'Varanasi Handloom Cluster (GI #99)',
    materials: ['Pure Mulberry Silk', 'Tested Gold/Silver Zari', 'Natural Plant Mordants'],
    stockQuantity: 5,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-UP-0099',
    tags: ['Banarasi Silk', 'Kadhwa Weave', 'Handloom', 'GI Certified', 'Heirloom'],
    detectedLanguage: 'hi',
    audioTranscript: 'यह कढ़वा बुनाई का स्टोल है जिसमें पीछे कोई धागा नहीं छूटता। पूरे 25 दिन लगे हैं इसे तैयार करने में।',
    createdAt: '2026-08-22T09:00:00Z'
  },
  {
    id: 'prod-madhubani-04',
    title: 'Madhubani Handpainted "Tree of Life" Parchment Art',
    titleHi: 'मधुबनी हस्तचित्रित "जीवन का वृक्ष" (गोबर लिपे बांस कागज़ पर)',
    description: 'Fine-nib Kachni style folk painting depicting the sacred cosmic tree, birds, and flora using natural plant dyes and cow dung wash on handmade rag paper.',
    descriptionHi: 'हाथ से बने कागज़ पर प्राकृतिक वनस्पति रंगों और बांस की कलम से उकेरी गई मधुबनी कछनी चित्रकला।',
    culturalStory: 'Originating in the Mithila region of Bihar, Madhubani painting was traditionally practiced by women on the freshly plastered mud walls of their huts during weddings and harvest festivals.',
    culturalStoryHi: 'मिथिला की महिलाओं द्वारा सदियों से दीवारों पर प्राकृतिक रंगों जैसे हल्दी, नील और काजल से बनाई जाने वाली शुभ चित्रकला।',
    category: 'painting',
    priceMin: 1800,
    priceMax: 2400,
    finalPrice: 2100,
    images: [
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Bina Devi Paswan',
    artisanLocation: 'Jitwarpur, Madhubani, Bihar',
    artisanPhone: '+91 93041 55231',
    craftOrigin: 'Mithila Region, Bihar (GI #105)',
    materials: ['Handmade Bamboo Paper', 'Indigo Plant Dye', 'Turmeric Ochre', 'Lampblack Ink'],
    stockQuantity: 15,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-BR-0105',
    tags: ['Madhubani', 'Mithila Folk Art', 'Natural Dyes', 'Tree of Life', 'GI Heritage'],
    detectedLanguage: 'hi',
    audioTranscript: 'यह चित्रकला हमने घर में बनाई है, प्राकृतिक हल्दी, काजल और नीम के पत्तों के रस से।',
    createdAt: '2026-08-28T16:40:00Z'
  },
  {
    id: 'prod-kala-cotton-05',
    title: 'Kutch Kala Cotton Handspun Organic Shawl',
    titleHi: 'कच्छ काला कॉटन प्राकृतिक हथकरघा शॉल',
    description: 'Indigenous rain-fed organic Kala cotton handwoven on traditional throw-shuttle pit looms by the Vankar community of Bhujodi.',
    descriptionHi: 'कच्छ के भुजोड़ी बुनकरों द्वारा वर्षा-आधारित जैविक काला कपास से बुनी गई पारंपरिक शॉल।',
    culturalStory: 'Kala cotton is an indigenous genetically pure Old World cotton from Kutch that requires zero pesticides or chemical fertilizers. Each geometric border is picked by hand on the loom.',
    culturalStoryHi: 'कच्छ की वर्षा-आधारित देशज कपास जो बिना रासायनिक खाद के उगती है। इसके किनारे हाथों से पारंपरिक नमूनों में बुने गए हैं।',
    category: 'textiles',
    priceMin: 2800,
    priceMax: 3600,
    finalPrice: 3200,
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Pravin Vankar',
    artisanLocation: 'Bhujodi, Kutch, Gujarat',
    artisanPhone: '+91 99791 22340',
    craftOrigin: 'Kutch Artisan Cluster, Gujarat',
    materials: ['100% Organic Kala Cotton', 'Pomegranate Peel Yellow', 'Hardu Vegetable Dye'],
    stockQuantity: 9,
    status: 'live',
    giTagged: false,
    tags: ['Organic Cotton', 'Kutch Weaving', 'Sustainable', 'Handspun', 'Natural Dye'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-02T11:20:00Z'
  },
  {
    id: 'prod-channapatna-06',
    title: 'Channapatna Non-Toxic Lacquerware Wooden Stacking Birds',
    titleHi: 'चन्नपटना प्राकृतिक लाख रंगीन काष्ठ खिलौने (पक्षी)',
    description: 'Eco-friendly traditional wooden stacking puzzle crafted from locally harvested Ivory wood (Wrightia tinctoria) and finished with natural non-toxic vegetable lacquers.',
    descriptionHi: 'आइवरी की लकड़ी और प्राकृतिक लाख (हल्दी और नील) से बने बच्चों के लिए सुरक्षित खिलौने।',
    culturalStory: 'Originating during the reign of Tipu Sultan who invited Persian artisans to train local craftspeople, Channapatna woodcraft is known as the "Gombegala Ooru" (Toy Town) of India.',
    culturalStoryHi: 'टीपू सुल्तान के समय से प्रचलित चन्नपटना खिलौना कला। इसमें केवल प्राकृतिक वनस्पति रंगों का उपयोग होता है।',
    category: 'woodwork',
    priceMin: 750,
    priceMax: 1050,
    finalPrice: 890,
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Girish Gowda',
    artisanLocation: 'Channapatna, Ramanagara, Karnataka',
    artisanPhone: '+91 94812 66720',
    craftOrigin: 'Channapatna Craft Cluster (GI #01)',
    materials: ['Ivory Wood (Aale Mara)', 'Natural Lac Resin', 'Turmeric and Kumkum Dyes'],
    stockQuantity: 24,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-KA-0001',
    tags: ['Channapatna', 'GI Tagged', 'Eco Friendly Toys', 'Non Toxic', 'Woodcraft'],
    detectedLanguage: 'en',
    createdAt: '2026-09-08T08:15:00Z'
  },
  {
    id: 'prod-basketry-07',
    title: 'Handcrafted Palm Leaf & Sikki Grass Coiled Decorative Basket',
    titleHi: 'हस्तनिर्मित ताड़ के पत्ते और सिककी घास पारंपरिक सजावटी टोकरी',
    description: 'Meticulously hand-coiled and woven by rural women artisans using wild palm fronds and marsh grass with vibrant natural dyes.',
    descriptionHi: 'ग्रामीण महिला शिल्पियों द्वारा ताड़ के सूखे पत्तों और प्राकृतिक सिककी घास से हाथ से गूंथी गई पारंपरिक टोकरी।',
    culturalStory: 'Meticulously hand-coiled and woven by rural women artisans using wild palm fronds and marsh grass. The concentric spiral weave incorporates vibrant botanical magenta and turquoise dyes, creating durable, eco-friendly storage craft steeped in Indian coastal and rural heritage.',
    culturalStoryHi: 'ग्रामीण महिला शिल्पियों द्वारा ताड़ के सूखे पत्तों और प्राकृतिक सिककी घास से हाथ से गूंथी गई पारंपरिक टोकरी। इसमें प्राकृतिक वनस्पतियों से तैयार किए गए रंगों का कलात्मक उपयोग किया गया है।',
    category: 'basketry',
    priceMin: 650,
    priceMax: 1150,
    finalPrice: 890,
    images: [
      'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Kamla Devi',
    artisanLocation: 'Madhubani & Coastal Crafts Guild, Bihar',
    artisanPhone: '+91 98350 77120',
    craftOrigin: 'Mithila & Coastal Basketry Cluster (GI Tagged)',
    materials: ['Wild Palm Leaf Strips', 'Natural Sikki Grass', 'Botanical Magenta & Turquoise Dyes'],
    stockQuantity: 18,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-BR-0108',
    tags: ['Sikki Grass', 'Palm Leaf', 'Coiled Basketry', 'Eco Friendly', 'GI Certified'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-10T10:00:00Z'
  },
  {
    id: 'prod-jewelry-08',
    title: 'Cuttack 925 Silver Filigree (Tarakasi) Heritage Floral Pendant',
    titleHi: 'कटक 925 चांदी तारकशी पारंपरिक पुष्प पेंडेंट',
    description: 'Breathtaking silver filigree medallion handcrafted from 0.3mm hand-drawn silver wires twisted into gossamer swirls by master silversmiths.',
    descriptionHi: 'कटक के स्वर्णकारों द्वारा बाल से भी पतले 925 शुद्ध चांदी के तारों को हाथ से मोड़कर बनाया गया जालीदार पेंडेंट।',
    culturalStory: 'Rooted in 500-year-old traditions of Cuttack, Tarakasi involves drawing fine silver into spider-web-thin threads, forming delicate curling florets with tweezer dexterity, and uniting them with pinpoint silver soldering.',
    culturalStoryHi: 'कटक की ५०० वर्ष पुरानी तारकशी कला जिसमें चांदी के महीन तारों से हाथ की चिमटी द्वारा जालीदार आभूषण गढ़े जाते हैं।',
    category: 'jewelry',
    priceMin: 3200,
    priceMax: 4500,
    finalPrice: 3800,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Prasanna Kumar Sahoo',
    artisanLocation: 'Nayasarak, Cuttack, Odisha',
    artisanPhone: '+91 94370 21540',
    craftOrigin: 'Cuttack Tarakasi Cluster, Odisha (GI #547)',
    materials: ['925 Sterling Silver', 'Hand-Twisted Silver Wire', 'Natural Borax Flux'],
    stockQuantity: 8,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-OD-0547',
    tags: ['Silver Filigree', 'Tarakasi', 'Cuttack GI Tag', '925 Silver', 'Heritage Jewelry'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-12T11:30:00Z'
  },
  {
    id: 'prod-leather-09',
    title: 'Authentic Vegetable-Tanned Kolhapuri Leather Footwear',
    titleHi: 'प्रामाणिक पारंपरिक वनस्पति-रंजित कोल्हापुरी चप्पल',
    description: 'Handcrafted durable footwear made with vegetable-tanned natural hide, braided leather cording, and cured in cold-pressed mustard oil.',
    descriptionHi: 'बबूल की छाल और हरड़ से प्राकृतिक रूप से पकाए गए चमड़े से हाथ द्वारा सिली गई मजबूत पारंपरिक कोल्हापुरी चप्पल।',
    culturalStory: 'Originating in the 12th century under King Bijjana, authentic Kolhapuris are 100% biodegradable, made without chemical chrome tanning, hand-punched, and braided with leather chords that soften and mold to the wearer’s feet.',
    culturalStoryHi: '१२वीं शताब्दी से चली आ रही कोल्हापुरी चप्पल परंपरा जो पूरी तरह प्राकृतिक सामग्रियों और हाथ की सिलाई से बनती है।',
    category: 'leather',
    priceMin: 1600,
    priceMax: 2400,
    finalPrice: 1950,
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Santosh Kamble',
    artisanLocation: 'Subhash Nagar, Kolhapur, Maharashtra',
    artisanPhone: '+91 98220 91823',
    craftOrigin: 'Kolhapur Leather Cluster, Maharashtra (GI #297)',
    materials: ['Vegetable Tanned Leather', 'Acacia Babool Bark', 'Cotton Cord', 'Mustard Oil'],
    stockQuantity: 14,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-MH-0297',
    tags: ['Kolhapuri', 'GI Certified #297', 'Vegetable Tanned', 'Hand Stitched', 'Eco Leather'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-14T09:15:00Z'
  },
  {
    id: 'prod-terracotta-10',
    title: 'Bankura GI-Certified Terracotta Long-Neck Horse Figurine',
    titleHi: 'बांकुड़ा जीआई प्रमाणित टेराकोटा लंबा गर्दन अश्व शिल्प',
    description: 'Iconic Bengali terracotta sculpture turned on village potters wheels, assembled by hand, and fired in indigenous subterranean kilns.',
    descriptionHi: 'बांकुड़ा के कुंभकार शिल्पियों द्वारा नदी की मिट्टी से चाक पर गढ़ा गया प्रसिद्ध पारंपरिक टेराकोटा घोड़ा।',
    culturalStory: 'Originating in Panchmura village, the Bankura horse is celebrated worldwide for its erect ears, symmetrical ornamentation, and hollow terracotta structure that represents tribal folklore and devotion.',
    culturalStoryHi: 'पंचमुड़ा गांव का प्रसिद्ध बांकुड़ा टेराकोटा घोड़ा जो भारतीय हस्तशिल्प का अंतरराष्ट्रीय प्रतीक है।',
    category: 'terracotta',
    priceMin: 950,
    priceMax: 1650,
    finalPrice: 1250,
    images: [
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Bipul Kumbhakar',
    artisanLocation: 'Panchmura, Bankura, West Bengal',
    artisanPhone: '+91 97321 44580',
    craftOrigin: 'Bankura Terracotta Cluster, West Bengal (GI #44)',
    materials: ['Alluvial River Clay', 'Rice Husk Ash', 'Natural Red Ochre'],
    stockQuantity: 20,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-WB-0044',
    tags: ['Bankura Horse', 'Terracotta', 'GI Tagged #44', 'Clay Art', 'Handmade'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-16T14:00:00Z'
  },
  {
    id: 'prod-stonecraft-11',
    title: 'Agra Marble Inlay (Pietra Dura) Floral Decorative Plate',
    titleHi: 'आगरा मकराना संगमरमर पच्चीकारी सजावटी थाली (पिएत्रा ड्यूरा)',
    description: 'Exquisite Makrana white marble tabletop plate inlaid with polished lapis lazuli, malachite, and carnelian semiprecious gemstones.',
    descriptionHi: 'मकराना संगमरमर में हाथ से तराशकर असली लापिस लाजुली और गोमेद पत्थरों को जड़कर तैयार की गई मुगलकालीन पच्चीकारी थाली।',
    culturalStory: 'Descended from Mughal imperial artisans who adorned the Taj Mahal, Agra Pietra Dura artisans hand-grind semiprecious stones against emery wheels and bond them seamlessly into channeled marble with traditional unani adhesive.',
    culturalStoryHi: 'ताजमहल की नक्काशी करने वाले कारीगरों के वंशजों द्वारा कीमती पत्थरों को संगमरमर में जड़कर बनाई गई ऐतिहासिक कला।',
    category: 'stonecraft',
    priceMin: 2800,
    priceMax: 4800,
    finalPrice: 3600,
    images: [
      'https://images.unsplash.com/photo-1599818816934-8c85770020bc?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Irfan Khan',
    artisanLocation: 'Gokulpura, Agra, Uttar Pradesh',
    artisanPhone: '+91 98971 63201',
    craftOrigin: 'Agra Marble Craft Cluster, Uttar Pradesh (GI #52)',
    materials: ['Makrana White Marble', 'Lapis Lazuli', 'Malachite', 'Carnelian'],
    stockQuantity: 6,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-UP-0052',
    tags: ['Marble Inlay', 'Pietra Dura', 'Agra GI #52', 'Semiprecious Stones', 'Heritage'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-18T10:45:00Z'
  },
  {
    id: 'prod-embroidery-12',
    title: 'Lucknowi Chikankari Hand-Embroidered Pure Mulmul Kurta Fabric',
    titleHi: 'लखनवी चिकनकारी हस्त-कशीदाकारी मलमल कुर्ता वस्त्र',
    description: 'Delicate hand-embroidered shadow work fabric crafted with pure resham silk threads on airy gossamer mulmul cotton.',
    descriptionHi: 'लखनऊ की महिला कारीगरों द्वारा शुद्ध मलमल पर बकिया और फंदा टांकों से सुई द्वारा की गई महीन चिकनकारी।',
    culturalStory: 'Introduced by Empress Nur Jahan, Lucknow Chikankari is an ethereal needlecraft consisting of 32 distinct stitches that turn fine white muslin into an interplay of delicate shadows and raised botanical textures.',
    culturalStoryHi: 'मल्लिका नूरजहाँ के समय से चली आ रही लखनवी चिकनकारी जिसमें ३२ प्रकार के टांकों से मलमल पर जादू बिखेरा जाता है।',
    category: 'embroidery',
    priceMin: 2400,
    priceMax: 3800,
    finalPrice: 2950,
    images: [
      'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Shabana Bano',
    artisanLocation: 'Chowk, Lucknow, Uttar Pradesh',
    artisanPhone: '+91 94150 82741',
    craftOrigin: 'Lucknow Chikankari Cluster, Uttar Pradesh (GI #119)',
    materials: ['Pure Mulmul Cotton', 'Resham Silk Floss', 'Metallic Badla Wire'],
    stockQuantity: 11,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-UP-0119',
    tags: ['Lucknow Chikankari', 'GI #119', 'Hand Embroidery', 'Pure Mulmul', 'Awadh'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-19T13:20:00Z'
  },
  {
    id: 'prod-paper-mache-13',
    title: 'Kashmir Hand-Painted Papier-Mâché Heritage Floral Box',
    titleHi: 'कश्मीर हस्तचित्रित पेपर मेशी पुष्प डिबिया (असली सोने का वर्क)',
    description: 'Intricately painted Kashmiri papier-mâché jewelry box molded from recycled paper pulp, stone-burnished, and gilded with real 24k gold leaf.',
    descriptionHi: 'कागज की लुगदी से ढाली गई और पत्थर से घिसकर असली सोने के वर्क तथा वनस्पति रंगों से चित्रित कश्मीरी डिबिया।',
    culturalStory: 'Brought from Samarkand to the Kashmir Valley in the 14th century, Kashmiri papier-mâché (Kari-kalamdani) marries sustainable paper molding with breathtaking miniature floral Naqashi painting.',
    culturalStoryHi: '१४वीं शताब्दी में समरकंद से कश्मीर आई पेपर मेशी कला, जिसमें कागज की लुगदी और सुनहरी नक्शीकारी का अनूठा संगम है।',
    category: 'paper_mache',
    priceMin: 1200,
    priceMax: 2100,
    finalPrice: 1650,
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Ghulam Hassan Mir',
    artisanLocation: 'Zadibal, Srinagar, Jammu & Kashmir',
    artisanPhone: '+91 94190 31278',
    craftOrigin: 'Kashmir Papier Mache Cluster, J&K (GI #81)',
    materials: ['Mashed Paper Pulp', 'Rice Adhesive', 'Chalk Gesso', '24k Gold Leaf'],
    stockQuantity: 15,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-JK-0081',
    tags: ['Kashmir Papier Mache', 'GI #81', 'Gold Foil', 'Hand Painted', 'Valley Art'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-20T15:10:00Z'
  },
  {
    id: 'prod-glasscraft-14',
    title: 'Firozabad Hand-Blown Luster Glass Lamp / Vessel',
    titleHi: 'फिरोज़ाबाद हस्तनिर्मित कांच दीप व कलात्मक पात्र',
    description: 'Iridescent hand-blown glass artifact hand-shaped with open furnace blowpipes at 1200°C by ancestral glassmakers.',
    descriptionHi: 'फिरोज़ाबाद के कांच शिल्पियों द्वारा १२00 डिग्री तापमान पर मुंह की फूंक और चिमटों से ढाला गया बहुरंगी पारदर्शी कांच दीप।',
    culturalStory: 'Known globally as the City of Glass and Bangles, Firozabad artisans shape glowing molten glass blobs into delicate, luminous vessels using breath control and wooden paddles without machine presses.',
    culturalStoryHi: 'फिरोज़ाबाद के उस्ताद कांच शिल्पियों की सदियों पुरानी फूंक कला, जिससे भट्टी में पिघले कांच को बिना सांचे के मनचाहा आकार दिया जाता है।',
    category: 'glasscraft',
    priceMin: 850,
    priceMax: 1550,
    finalPrice: 1150,
    images: [
      'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Mukesh Chandra',
    artisanLocation: 'Sadar Bazar, Firozabad, Uttar Pradesh',
    artisanPhone: '+91 98371 52090',
    craftOrigin: 'Firozabad Glass Cluster, Uttar Pradesh',
    materials: ['Recycled Silica Glass', 'Natural Soda Ash', 'Cobalt Colorant'],
    stockQuantity: 22,
    status: 'live',
    giTagged: false,
    tags: ['Firozabad Glass', 'Hand Blown', 'Molten Glass', 'Artisan Vessel', 'Lusterware'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-21T09:30:00Z'
  },
  {
    id: 'prod-carpets-15',
    title: 'Bhadohi Pure Bikaneri Wool Hand-Knotted Heritage Rug',
    titleHi: 'भदोही शुद्ध बीकानेरी ऊन से बुना हस्तनिर्मित हेरिटेज कालीन',
    description: 'Timeless hand-knotted woolen rug woven with 120+ knots per square inch on vertical pit looms with natural madder and indigo dyes.',
    descriptionHi: 'भदोही के बुनकरों द्वारा ऊन की एक-एक गांठ हाथ से बांधकर और प्राकृतिक वनस्पति रंगों में रंगकर तैयार किया गया कीमती कालीन।',
    culturalStory: 'Bhadohi is Asia’s largest handmade carpet hub. Dating back to Emperor Akbar, each rug is woven knot by knot according to traditional talim graph-cards, taking months of patient master weaver labor.',
    culturalStoryHi: 'एशिया का सबसे बड़ा हस्तनिर्मित कालीन केंद्र भदोही। तालीम के आधार पर एक-एक गांठ को हाथ से बांधकर महीनों की मेहनत से तैयार किया जाता है।',
    category: 'carpets',
    priceMin: 4800,
    priceMax: 8500,
    finalPrice: 6200,
    images: [
      'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80'
    ],
    artisanId: 'artisan-ramswaroop',
    artisanName: 'Naseem Ansari',
    artisanLocation: 'Khamaria, Bhadohi, Uttar Pradesh',
    artisanPhone: '+91 94152 70812',
    craftOrigin: 'Bhadohi-Mirzapur Carpet Cluster (GI #128)',
    materials: ['Indigenous Bikaneri Wool', 'Handspun Cotton Warp', 'Vegetable Madder Dye'],
    stockQuantity: 5,
    status: 'live',
    giTagged: true,
    giTagNumber: 'GI-UP-0128',
    tags: ['Bhadohi Carpet', 'GI #128', 'Hand Knotted', 'Pure Wool', 'Heirloom Rug'],
    detectedLanguage: 'hi',
    createdAt: '2026-09-22T12:00:00Z'
  }
];

export const initialInquiries: Inquiry[] = [
  {
    id: 'inq-01',
    productId: 'prod-surahi-01',
    productTitle: 'Jaipur Blue Pottery Floral Surahi',
    productImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=300&q=80',
    artisanId: 'artisan-ramswaroop',
    buyerName: 'Vikramaditya Patel',
    buyerPhone: '+91 98980 12345',
    buyerEmail: 'vikram.heritage@gmail.com',
    channel: 'call',
    message: 'Hello Ramswaroop Ji, we want to place an order of 15 handcrafted surahis for our heritage resort dining hall in Udaipur. Please arrange a callback.',
    status: 'new',
    createdAt: '2026-09-20T14:30:00Z',
    replies: []
  },
  {
    id: 'inq-02',
    productId: 'prod-banarasi-03',
    productTitle: 'Handloom Pure Mulberry Silk Banarasi Kadhwa Stole',
    productImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=300&q=80',
    artisanId: 'artisan-ramswaroop',
    buyerName: 'Priya Sundaram',
    buyerPhone: '+91 98450 77123',
    buyerEmail: 'priya.sundaram@designstudio.in',
    channel: 'chat',
    message: 'Namaste! Can the zari border pattern be slightly customized with peacock motifs for a wedding trousseau? How many days lead time is required?',
    status: 'new',
    createdAt: '2026-09-21T18:45:00Z',
    replies: [
      {
        id: 'rep-01',
        sender: 'artisan',
        message: 'Namaste Priya Ji! Yes, peacock motifs can be incorporated on our pit loom. It will take 18 days to weave by hand.',
        timestamp: '2026-09-22T08:10:00Z'
      }
    ]
  },
  {
    id: 'inq-03',
    productId: 'prod-dhokra-02',
    productTitle: 'Bastar Lost-Wax Bell Metal (Dhokra) Nandi Figurine',
    productImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=300&q=80',
    artisanId: 'artisan-ramswaroop',
    buyerName: 'Rahul Mehra',
    buyerPhone: '+91 99100 45678',
    channel: 'sms',
    message: 'Interested in Bastar Dhokra Nandi. Confirming availability for immediate dispatch to South Extension, New Delhi. Is packaging shatter-proof?',
    status: 'contacted',
    createdAt: '2026-09-19T11:20:00Z',
    replies: []
  }
];

export const salesRecords6Months: SalesRecord[] = [
  { month: 'Apr', revenue: 54000, orders: 28 },
  { month: 'May', revenue: 68500, orders: 36 },
  { month: 'Jun', revenue: 72000, orders: 41 },
  { month: 'Jul', revenue: 86000, orders: 49 },
  { month: 'Aug', revenue: 98500, orders: 58 },
  { month: 'Sep', revenue: 106000, orders: 63 }
];

export const categoryDistribution: CategoryDistribution[] = [
  { category: 'Blue Pottery & Ceramics', percentage: 42, itemCount: 18 },
  { category: 'Dhokra & Bell Metal', percentage: 28, itemCount: 12 },
  { category: 'Handloom & Textiles', percentage: 18, itemCount: 8 },
  { category: 'Folk Paintings', percentage: 12, itemCount: 5 }
];
